services:
  db:
    image: mysql:lts
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sodality
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
    volumes:
      - sodality-db:/var/lib/mysql

  sodality:
    build: .
    restart: unless-stopped
    ports:
      - 5173:5173
      - 3001:3001
    depends_on:
      - db
    links:
      - db

volumes:
  sodality-db: